#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="stable24/moodle-latest-24.tgz"
URL="http://downloads.sourceforge.net/project/moodle/Moodle/$VERSION"

dl $URL /usr/local/src


