#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="stable34/moodle-latest-34.tgz"
URL="https://download.moodle.org/download.php/direct/$VERSION"

dl $URL /usr/local/src


