#!/bin/bash -ex

WEBROOT=/var/www/moodle
DATAROOT=/var/www/moodledata

DB_NAME=moodle
DB_USER=moodle
DB_PASS=$(mcookie)

ADMIN_USER="admin"
ADMIN_PASS=turnkey
MOODLE_COMMIT=b07dd04b40ece3b2d43b2e6ec1213db2a997df7f

# start mysql
systemctl start mysql

# create database
mysqladmin create $DB_NAME

# create database user with privileges on the database
MYSQL_BATCH="mysql --batch --execute"
$MYSQL_BATCH "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS';"
$MYSQL_BATCH "flush privileges;"

# setup apache configuration and complete installation
a2dissite 000-default
a2ensite moodle
a2enmod rewrite
a2enmod headers

git init "$WEBROOT"
git -C "$WEBROOT" remote add origin https://github.com/moodle/moodle.git
git -C "$WEBROOT" fetch --depth 1 origin "$MOODLE_COMMIT"
git -C "$WEBROOT" checkout --detach "$MOODLE_COMMIT"
test "$(git -C "$WEBROOT" rev-parse HEAD)" = "$MOODLE_COMMIT"

cd $WEBROOT
php admin/cli/install.php \
    --chmod=750 \
    --lang=en \
    --wwwroot="http://127.0.0.1" \
    --dataroot=$DATAROOT \
    --dbtype=mariadb \
    --dbhost=localhost \
    --dbname=$DB_NAME \
    --dbuser=$DB_USER \
    --dbpass="$DB_PASS" \
    --prefix="" \
    --fullname="TurnKey Moodle" \
    --shortname=moodle \
    --adminuser=$ADMIN_USER \
    --adminpass=$ADMIN_PASS \
    --adminemail=admin@example.com \
    --upgradekey= \
    --non-interactive \
    --agree-license

# Executable Moodle and theme/plugin code is root-owned. Only Moodle's data
# directory remains writable by the web service.
chown -R root:root "$WEBROOT"
find "$WEBROOT" -type d -exec chmod 0755 {} +
find "$WEBROOT" -type f -exec chmod 0644 {} +
chown root:www-data "$WEBROOT/config.php"
chmod 0640 "$WEBROOT/config.php"
chown -R www-data:www-data "$DATAROOT"
find "$DATAROOT" -type d -exec chmod 0750 {} +
find "$DATAROOT" -type f -exec chmod 0640 {} +

## tweak config

# configure moodle to use dynamic hostname and ssl (webroot)
sed -i "s|\$CFG->wwwroot \(.*\)|\$protocol='http://';\n\$hostname='127.0.0.1';\nif (isset(\$_SERVER['HTTPS'])) { \$protocol='https://'; }\nif (isset(\$_SERVER['HTTP_HOST'])) { \$hostname=\$_SERVER['HTTP_HOST']; }\n\$CFG->wwwroot = \$protocol.\$hostname;\n|" $WEBROOT/config.php

# prevent setting of executable paths via Admin UI (locks down possible privilege escalation)
sed -i "/'admin';$/ a \$CFG->preventexecpath = true;" $WEBROOT/config.php

# set paths to utils
mysql <<EOF
USE $DB_NAME;
UPDATE config SET value = '1' WHERE name = 'loginhttps';
UPDATE config SET value = '127.0.0.1' WHERE name = 'smtphosts';
UPDATE config SET value = 'noreply@example.com' WHERE name = 'noreplyaddress';
UPDATE config SET value = '/usr/bin/du' WHERE name = 'pathtodu';
UPDATE config SET value = '/usr/bin/aspell' WHERE name = 'aspellpath';
UPDATE config SET value = '/usr/bin/php' WHERE name = 'pathtophp';
UPDATE config SET value = '/usr/bin/dot' WHERE name = 'pathtodot';
UPDATE config SET value = '/usr/bin/gs' WHERE name = 'pathtogs';
UPDATE config SET value = '/usr/bin/pdftoppm' WHERE name = 'pathtopdftoppm';
UPDATE config SET value = '/usr/bin/python3' WHERE name = 'pathtopython';
EOF

# disable user delete - removes hyped up "critical" warning
# - see https://tracker.moodle.org/browse/MDL-67852 for more info
mysql <<EOF
USE $DB_NAME;
DELETE FROM role_capabilities WHERE capability = "tool/dataprivacy:requestdelete";
EOF

# stop mysql server
systemctl stop  mysql
