#!/bin/bash -e
# regenerate moodle mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

updateconf() {
    CONF=/var/www/moodle/config.php
    sed -i "\|$1|s|=.*|= '$2';|" $CONF
}

updateconf '\$CFG->dbpass' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=moodle --pass="$PASSWORD"
