#!/bin/bash -e
# regenerate moodle mysql password

. /etc/default/inithooks

SALT=$(mcookie)
PASSWORD=$(mcookie)

updateconf() {
    CONF=/var/www/moodle/config.php
    sed -i "s/\(.*\)$1\(.*\)';/$1 = '$2';/;" $CONF
}

updateconf '\$CFG->passwordsaltmain' $SALT
updateconf '\$CFG->dbpass' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=moodle --pass="$PASSWORD"

