ServerName localhost

ErrorDocument 404 /error/index.php

# This sends any 403 from apache through to the same page, but also
# overrides the http status with 404 instead for better security.
ErrorDocument 403 /error/index.php?code=404

<VirtualHost *:80>
    UseCanonicalName Off
    ServerAdmin  webmaster@localhost
    DocumentRoot /var/www/moodle/public/
    RewriteEngine On
    RewriteCond %{HTTP_HOST} !=localhost
    RewriteCond %{REMOTE_ADDR} !=127.0.0.1
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    ServerAdmin  webmaster@localhost
    DocumentRoot /var/www/moodle/public/
    RewriteEngine On
    RewriteRule "(\/vendor\/)" - [F,NC]
    RewriteRule "(\/node_modules\/)" - [F,NC]
    RewriteRule "(\/bin\/)" - [F,NC]
    RewriteRule "(\/cache\/)" - [F,NC]
    RewriteRule "(\/local\/)" - [F,NC]
    RewriteRule "(\/tests\/)" - [F,NC]
    RewriteRule "(\/behat\/)" - [F,NC]
    RewriteRule "(\/fixtures\/)" - [F,NC]
    RewriteRule "(^|/)\.(?!well-known\/)" - [F,NC]
    RewriteRule "(composer\.(json|lock))" - [F,NC]
    RewriteRule "(package\.(json|lock))" - [F,NC]
    RewriteRule "(config\.php)" - [F,NC]
    RewriteRule "(.*\.bak)" - [F,NC]
    RewriteRule "(.*\.old)" - [F,NC]
    RewriteRule "(.*\.orig)" - [F,NC]
    RewriteRule "(\.lock)" - [F,NC]
    RewriteRule "(.*\.orig|environment\.xml)" - [F,NC]
    RewriteRule "(\/environment.xml)" - [F,NC]
    RewriteRule "(\/install.xml)" - [F,NC]
    RewriteRule "(\/README)" - [F,NC]
    RewriteRule "(\/readme)" - [F,NC]
    RewriteRule "(\/moodle_readme)" - [F,NC]
    RewriteRule "(\/upgrade\.txt)" - [F,NC]
    RewriteRule "(phpunit\.xml\.dist)" - [F,NC]
</VirtualHost>

<Directory /var/www/moodle/public/>
    Options +FollowSymLinks -Indexes
    AllowOverride All
    Require all granted
</Directory>
